// Mirrors the four Figma variable modes from the token files.
// Token mapping per component:
//   FAB pill bg      → c-button.text.primary
//   FAB label        → c-button.text.tertiary
//   Sheet bg         → surface.base
//   Heading          → text.primary
//   Body             → text.secondary
//   Chip bg/border   → c-button.surface.secondary / ghosted-border
//   Next button      → c-button.surface.primary / text.primary

export const THEMES = {
  lighter: {
    fabBg:        '#FFFFFF',
    fabLabel:     '#000000',
    fabShadow:    '0 4px 32px rgba(0,0,0,0.16)',
    badgeBg:      '#1F1F1F',
    badgeBorder:  '#FFFFFF',
    badgeIcon:    '#FFFFFF',
    sheetBg:      '#FFFFFF',
    heading:      '#000000',
    body:         '#323030',
    chipBg:       '#F2F2F2',
    chipBorder:   '#DBDBDB',
    chipText:     '#000000',
    progressTrack:'#E8E8E8',
    progressFill: '#000000',
    footerBorder: '#F2F2F2',
    nextBg:       '#131313',
    nextIcon:     '#FFFFFF',
    closeColor:   '#000000',
    backdrop:     'rgba(0,0,0,0.4)',
  },
  light: {
    fabBg:        '#FAFAFA',
    fabLabel:     '#080808',
    fabShadow:    '0 4px 32px rgba(0,0,0,0.18)',
    badgeBg:      '#1F1F1F',
    badgeBorder:  '#FFFFFF',
    badgeIcon:    '#FFFFFF',
    sheetBg:      '#FAFAFA',
    heading:      '#080808',
    body:         '#474646',
    chipBg:       '#E8E8E8',
    chipBorder:   '#CCCCCC',
    chipText:     '#080808',
    progressTrack:'#DBDBDB',
    progressFill: '#080808',
    footerBorder: '#F2F2F2',
    nextBg:       '#131313',
    nextIcon:     '#FFFFFF',
    closeColor:   '#080808',
    backdrop:     'rgba(0,0,0,0.5)',
  },
  dark: {
    fabBg:        '#000000',
    fabLabel:     '#FAFAFA',
    fabShadow:    '0 4px 32px rgba(0,0,0,0.4)',
    badgeBg:      '#1F1F1F',
    badgeBorder:  '#FFFFFF',
    badgeIcon:    '#FFFFFF',
    sheetBg:      '#1F1F1F',
    heading:      '#FAFAFA',
    body:         '#CCCCCC',
    chipBg:       '#2E2E2E',
    chipBorder:   '#5C5C5C',
    chipText:     '#FAFAFA',
    progressTrack:'#323030',
    progressFill: '#FAFAFA',
    footerBorder: '#2E2E2E',
    nextBg:       '#F2F2F2',
    nextIcon:     '#000000',
    closeColor:   '#FAFAFA',
    backdrop:     'rgba(0,0,0,0.6)',
  },
  darker: {
    fabBg:        '#000000',
    fabLabel:     '#FFFFFF',
    fabShadow:    '0 4px 32px rgba(0,0,0,0.5)',
    badgeBg:      '#080808',
    badgeBorder:  '#FFFFFF',
    badgeIcon:    '#FFFFFF',
    sheetBg:      '#080808',
    heading:      '#FFFFFF',
    body:         '#E8E8E8',
    chipBg:       '#131313',
    chipBorder:   '#474646',
    chipText:     '#FFFFFF',
    progressTrack:'#1F1F1F',
    progressFill: '#FFFFFF',
    footerBorder: '#131313',
    nextBg:       '#F2F2F2',
    nextIcon:     '#000000',
    closeColor:   '#FFFFFF',
    backdrop:     'rgba(0,0,0,0.75)',
  },
}
